module.exports = [
    { name: 'Boring', tier: '2' },
    { name: 'Aether', tier: '2' },
    { name: 'Healthy', tier: '2' },
    { name: 'Happyhands', tier: '2' },
    { name: 'Kitsune', tier: '2' },
    { name: 'Kitsune2', tier: '2' },
    { name: 'Wood', tier: '2' },
    { name: 'Fruits', tier: '2' },
    { name: 'Memes', tier: '2' },
    { name: 'Vegetables', tier: '2' },
    { name: 'Beginner', tier: '2' },
    { name: 'Sunset', tier: '2' },
    { name: 'Pandemonium', tier: '2' },
    { name: 'Love Spliff', tier: '2' },
    { name: 'Aircontrol', tier: '2' },
    { name: 'Boring', tier: '2' },
    { name: 'Aether', tier: '2' },
    { name: 'Healthy', tier: '2' },
    { name: 'Happyhands', tier: '2' },
    { name: 'Kitsune', tier: '2' },
    { name: 'Kitsune2', tier: '2' },
    { name: 'Wood', tier: '2' },
    { name: 'Fruits', tier: '2' },
    { name: 'Memes', tier: '2' },
    { name: 'Vegetables', tier: '2' },
    { name: 'Beginner', tier: '2' },
    { name: 'Sunset', tier: '2' },
    { name: 'Pandemonium', tier: '2' },
    { name: 'Love Spliff', tier: '2' },
    { name: 'Aircontrol', tier: '2' },
];