module.exports = [
    { map: 'Boring', time: 23.52, ranking: { allTime: false, weekly: true, monthly: false } },
    { map: 'Vegetables', time: 23.52, ranking: { allTime: false, weekly: false, monthly: false } },
    { map: 'Healthy', time: 23.52, ranking: { allTime: false, weekly: true, monthly: false } },
    { map: 'Memes', time: 23.52, ranking: { allTime: true, weekly: false, monthly: true } },
    { map: 'Aether', time: 23.52, ranking: { allTime: false, weekly: true, monthly: true } },
    { map: 'Vegetables', time: 23.52, ranking: { allTime: false, weekly: false, monthly: false } },
    { map: 'Kitsune2', time: 23.52, ranking: { allTime: true, weekly: true, monthly: false } },
    { map: 'Fruits', time: 23.52, ranking: { allTime: true, weekly: true, monthly: true } },
    { map: 'Fruits', time: 23.52, ranking: { allTime: true, weekly: true, monthly: true } },
    { map: 'Beginner', time: 23.52, ranking: { allTime: false, weekly: true, monthly: true } },
    { map: 'Happyhands', time: 23.52, ranking: { allTime: false, weekly: true, monthly: false } },
    { map: 'Sunset', time: 23.52, ranking: { allTime: true, weekly: true, monthly: true } },
    { map: 'Pandemonium', time: 23.52, ranking: { allTime: false, weekly: false, monthly: false } },
    { map: 'Nocturne', time: 23.52, ranking: { allTime: true, weekly: true, monthly: false } },
    { map: 'Ducks Life', time: 23.52, ranking: { allTime: true, weekly: false, monthly: true } },
    { map: 'Aether', time: 23.52, ranking: { allTime: false, weekly: true, monthly: true } },
    { map: 'Kitsune', time: 23.52, ranking: { allTime: true, weekly: false, monthly: true } },
    { map: 'Ethreal', time: 23.52, ranking: { allTime: true, weekly: true, monthly: false } },
    { map: 'Boring', time: 23.52, ranking: { allTime: false, weekly: true, monthly: false } },
    { map: 'Vegetables', time: 23.52, ranking: { allTime: false, weekly: false, monthly: false } },
    { map: 'Healthy', time: 23.52, ranking: { allTime: false, weekly: true, monthly: false } },
    { map: 'Memes', time: 23.52, ranking: { allTime: true, weekly: false, monthly: true } },
    { map: 'Aether', time: 23.52, ranking: { allTime: false, weekly: true, monthly: true } },
    { map: 'Vegetables', time: 23.52, ranking: { allTime: false, weekly: false, monthly: false } },
    { map: 'Kitsune2', time: 23.52, ranking: { allTime: true, weekly: true, monthly: false } }
];